export const PIPE_UPDATE_PIPE_NUMBER = 'PIPE_UPDATE_PIPE_NUMBER';
export const PIPE_UPDATE_HEAT_NUMBER = 'PIPE_UPDATE_HEAT_NUMBER';
export const PIPE_LIST = 'PIPE_LIST';
export const PIPE_SAVE = 'PIPE_SAVE';
export const PIPE_LIST_SORT_COLUMN = 'PIPE_LIST_SORT_COLUMN';
export const PIPE_DIALOG_SET_DATA_A = 'PIPE_DIALOG_SET_DATA_A';
export const PIPE_DIALOG_SET_DATA_B = 'PIPE_DIALOG_SET_DATA_B';
export const PIPE_DIALOG_OPEN = 'PIPE_DIALOG_OPEN';
export const PIPE_DIALOG_CLOSE = 'PIPE_DIALOG_CLOSE';
export const PIPE_INFO = 'PIPE_INFO';

export const PROJECT_INCH = 'PROJECT_INCH';
export const PROJECT_VARIANCE = 'PROJECT_VARIANCE';
export const PROJECT_B_INCH = 'PROJECT_B_INCH';
export const PROJECT_B_VARIANCE = 'PROJECT_B_VARIANCE';
export const PROJECT_LIMIT_TYPE = 'PROJECT_LIMIT_TYPE';
export const PROJECT_CREATE = 'PROJECT_CREATE';
export const PROJECT_LIST = 'PROJECT_LIST';
export const PROJECT_SELECT = 'PROJECT_SELECT';
export const PROJECT_DELETED = 'PROJECT_DELETED';
export const PROJECT_DIALOG_SHOW = 'PROJECT_DIALOG_SHOW';
export const PROJECT_CREATE_DIALOG_SHOW = 'PROJECT_CREATE_DIALOG_SHOW';
export const PROJECT_UPDATE_NAME = 'PROJECT_UPDATE_NAME';
export const PROJECT_UPDATE_FIELD = 'PROJECT_UPDATE_FIELD';
export const PROJECT_UPDATE_FIELD_UNIT = 'PROJECT_UPDATE_FIELD_UNIT';
export const PROJECT_DISABLED = 'PROJECT_DISABLED';
export const PROJECT_FIELD_UNIT_INIT = 'PROJECT_FIELD_UNIT_INIT';
export const PROJECT_PIPE_OPTION_AUTOARCHIVE
    = 'PROJECT_PIPE_OPTION_AUTOARCHIVE';
export const PROJECT_PIPE_OPTION_AUTOGENERATE
    = 'PROJECT_PIPE_OPTION_AUTOGENERATE';
export const PROJECT_PIPE_OPTION_SINGLEEND
    = 'PROJECT_PIPE_OPTION_SINGLEEND';
export const PROJECT_TABLE_SHOW = 'PROJECT_TABLE_SHOW';

export const SCAN_UPDATE = 'SCAN_UPDATE';
export const SCAN_START = 'SCAN_START';
export const SCAN_DISCARD_A = 'SCAN_DISCARD_A';
export const SCAN_DISCARD_B = 'SCAN_DISCARD_B';
export const SCAN_FILE = 'SCAN_FILE';
export const SCAN_LIST_A = 'SCAN_LIST_A';
export const SCAN_ADD_A = 'SCAN_ADD_A';
export const SCAN_LIST_B = 'SCAN_LIST_B';
export const SCAN_ADD_B = 'SCAN_ADD_B';
export const SCAN_UPDATE_SAVE_A = 'SCAN_UPDATE_SAVE_A';
export const SCAN_UPDATE_SAVE_B = 'SCAN_UPDATE_SAVE_B';

export const HISTORY_LIST_A = 'HISTORY_LIST_A';
export const HISTORY_LIST_B = 'HISTORY_LIST_B';
export const HISTORY_ADD_A = 'HISTORY_ADD_A';
export const HISTORY_ADD_B = 'HISTORY_ADD_B';

export const GRAPH_DIALOG_OPEN = 'GRAPH_DIALOG_OPEN';
export const HISTORY_DIALOG_OPEN = 'HISTORY_DIALOG_OPEN';
export const RELOAD_GRAPH = 'RELOAD_GRAPH';

export const MANUAL_FIELD = 'MANUAL_FIELD';
export const MANUAL_FIELDS = 'MANUAL_FIELDS';
export const MANUAL_FIELD_UPDATE = 'MANUAL_FIELD_UPDATE';
export const MANUAL_FIELD_ADD = 'MANUAL_FIELD_ADD';
export const SHOW_SCANS = 'SHOW_SCANS';

export const SETTINGS_SET_WATCH_DIRECTORY_A
    = 'SETTINGS_SET_WATCH_DIRECTORY_A';
export const SETTINGS_SET_WATCH_DIRECTORY_B
    = 'SETTINGS_SET_WATCH_DIRECTORY_B';
export const SETTINGS_SET_OUTPUT_DIRECTORY_A
    = 'SETTINGS_SET_OUTPUT_DIRECTORY_A';
export const SETTINGS_SET_OUTPUT_DIRECTORY_B
    = 'SETTINGS_SET_OUTPUT_DIRECTORY_B';
export const TOPBAR_SETTINGS_SHOW = 'TOPBAR_SETTINGS_SHOW';
export const TOPBAR_MANUAL_FIELDS_SHOW = 'TOPBAR_MANUAL_FIELDS_SHOW';
export const PIPE_MANUAL_FIELD_SHOW = 'PIPE_MANUAL_FIELD_SHOW';
